// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Fre6TAUSo8wsSqeDjTQeA8NjTVMd7Ag',
    appId: '1:652886628273:web:ef3ed5de564f5d047e0f90',
    messagingSenderId: '652886628273',
    projectId: 'todoapp-c31f5',
    authDomain: 'todoapp-c31f5.firebaseapp.com',
    storageBucket: 'todoapp-c31f5.firebasestorage.app',
    measurementId: 'G-CDDZ8X1C6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj-pjLynK2QqXyaUQ19NDXm-ikqt6jqj0',
    appId: '1:652886628273:android:57a50e0daaeb1b787e0f90',
    messagingSenderId: '652886628273',
    projectId: 'todoapp-c31f5',
    storageBucket: 'todoapp-c31f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk5XEzOIpJlB0c98d1n1yYbndBb2ujbQY',
    appId: '1:652886628273:ios:06d9a9f0dd01ab937e0f90',
    messagingSenderId: '652886628273',
    projectId: 'todoapp-c31f5',
    storageBucket: 'todoapp-c31f5.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk5XEzOIpJlB0c98d1n1yYbndBb2ujbQY',
    appId: '1:652886628273:ios:06d9a9f0dd01ab937e0f90',
    messagingSenderId: '652886628273',
    projectId: 'todoapp-c31f5',
    storageBucket: 'todoapp-c31f5.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Fre6TAUSo8wsSqeDjTQeA8NjTVMd7Ag',
    appId: '1:652886628273:web:092c3bb78e9ee69c7e0f90',
    messagingSenderId: '652886628273',
    projectId: 'todoapp-c31f5',
    authDomain: 'todoapp-c31f5.firebaseapp.com',
    storageBucket: 'todoapp-c31f5.firebasestorage.app',
    measurementId: 'G-8VDENT12DR',
  );
}
